### ISSUE TITLE
analyzeDocumentForJudges soll maximal 5 judges herausgeben

### ISSUE THREAD

**Issue by sonofthefun** [ssephillip/LawStatsInAction#3]
Bei der Analyse der letzten Sätze, sollen am Ende nur die letzten fünf Richter herausgeben (also bei einer chronologischen Liste die ersten Einträge solange gelöscht werden bis es nur noch fünf sind).

**Comment by ssephillip** [comment]
Doppelte Richter (z.B. Urlaubsvertretung) werden ignoriert (der 2. Fund zählt nicht zu der Anzahl der 5 Richter)
