### ISSUE TITLE
Idee: Entscheidungen, die eine Mindestlänge unterschreiten nicht berücksichtigen?

### ISSUE THREAD

**Issue by beckedorf** [ssephillip/LawStatsInAction#5]
Vorher noch mit @sonofthefun besprechen! Aber könnte schon mal implementiert werden @ssephillip, wenn du Zeit hast. Ich würde als Maßstab nicht Anzahl der Sätze, sondern Anzahl der Zeichen oder Zeilenumbrüche nehmen.

**Comment by ssephillip** [comment]
ich kann leider nicht wirklich beurteilen ob das sinn macht oder nicht
was sagt @sonofthefun dazu?

**Comment by sonofthefun** [comment]
Da wir auch die 349 Abs. 2 StPO ohne Begründung brauchen, machen wir das nicht.
