### ISSUE TITLE
Decision Sentence in der Datenbank 'Current'

### ISSUE THREAD

**Issue by beckedorf** [ssephillip/LawStatsInAction#8]
Könnten wir den Decision Sentence auch in die Datenbank decisioncurrent schreiben? Ich glaube das könnte später praktisch sein.

**Comment by ssephillip** [comment]
Das ist eigentlich schon der Fall.
Bei ganz alten StudyTags gibt es das noch nicht. Die Daten davon sind aber sowieso nicht repräsentativ für die akutelle funktionalität der Software.
Die Einträge mit dem neusten Stand der Software fangen erst deutlich weiter unten an. DIe alten Sachen sind nur noch zum vergleichen da. Wenn ihr die nicht mehr braucht können die von mir aus gerne gelöscht werden.

**Comment by beckedorf** [comment]
Umso besser... :-)
